name: Java CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    # 建议升级到最新稳定版
      - name: Set up JDK 21
        uses: actions/setup-java@v4   # 建议升级到最新稳定版
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run PMD
        run: mvn pmd:pmd
      - name: Upload PMD results
        uses: actions/upload-artifact@v4  # 关键修复：升级到 v4
        with:
          name: pmd-reports
          path: target/reports/pmd/
      - name: Run tests
        run: mvn test
